### ISSUE TITLE
[Question/Suggestion] Lootsheet5e Dependency

### ISSUE THREAD

**Issue by Shuggaloaf** [marcstraube/foundryvtt-brodericks-compendium#1]
Hi there, I was getting ready to install when I saw this dependency. I tried Lootsheet awhile back and it did not play nice with my setup. I have no interest in re-installing it so I just had a few questions:

1) What functionality requires the use of the Lootsheet 5e mod? I understand what Lootsheet does, but is there actual _additional_ functionality that your mod adds that is based off of LS5e? 

2) ~~Will the mod still work OK without installing this?~~ Edit: I see that it does not. That's unfortunate. 

If this is purely for a personal design reason (IOW you just like the way that sheet looks), but it otherwise works fine with core (or other) sheets, I would suggest perhaps removing this dependency. You can always add a note to readme suggesting the use of it, but if it doesn't provide actual functionality specific to your mod, it could be seen by some as a barrier to using this mod.

**Comment by Shuggaloaf** [comment]
<h3><b>Update:</b></h3>
After playing around a bit, I removed the dependency from the module.json file. This allowed me to install and test your mod. Everything works fine without the Lootsheet 5e dependency. 

I understand that using LS5e in addition to your mod may give some functionality that _you_ prefer, but I realy feel that this is strongly on the side of "personal preference". After playing with the rolltables and browsing items, there is no loss in functionality _for your module_ by not using LS5e.


<h3><b>Better Rolltables</b></h3>
I do already use BR. Personally I love having item rolltables that allow you drag the rolltable result from chat onto a sheet. I personally think that this adds a lot to _any_ rolltable, and of course your mod as well. 
However, I have to wonder if this dependency doesn't also fall into the same category - recommend but _not_ actually required. Even though I love the mod, I would suggest removing this as a dependency as well. 

Dependencies should really only be used for mods that are absolutely required in order for your mod to function. I understand that without these 2 mods, you may view this as having less functionality, but this may be perfectly acceptable to others who may not want 1 or both of these mods installed.

<hr/>
Finally, I hope you take this as constructive criticism, not as me telling you what you need to do with your mod. At the end of the day it's your mod, but I do strongly feel these dependencies are unnecessary and may cause some users to simply not install it. If you're not sure, and want other opinions however, perhaps post this question on the Foundry and/or League of Extraordinary Foundry Devs Discord server. 

Thanks!

**Comment by marcstraube** [comment]
Hey @Shuggaloaf,
thanks for your input! You're right; both modules are not 100% necessary for the compendiums to work. I removed both of them from the dependencies. You can find the changes in version 1.2.0.
