### ISSUE TITLE
Error prevents importing Random Jungle Plant Table into world

### ISSUE THREAD

**Issue by T-Whiz** [marcstraube/foundryvtt-brodericks-compendium#10]
Hi, I love your module, thanks for sharing this. When attempting to import the tables into a world, the Random Jungle Plant Table isn't imported and displays an error. The other rolltables import as expected. Attached are some screen shots and a copy of the console log. I noticed in the Jungle table there are also some places where the numbeing has gaps or isn't sequential, I'm not sure whether it's related to the errors though. Attached screen shots of those as well.
[Error screen shots.pdf](https://github.com/marcstraube/foundryvtt-brodericks-compendium/files/10952022/Error.screen.shots.pdf)
[Jungle table screen shots.pdf](https://github.com/marcstraube/foundryvtt-brodericks-compendium/files/10952023/Jungle.table.screen.shots.pdf)
[console log.log](https://github.com/marcstraube/foundryvtt-brodericks-compendium/files/10952024/console.log.log)

**Comment by marcstraube** [comment]
Thanks for reporting the issue. I'm al little busy this month, but I'm taking a look at it as soon as I find some time.

**Comment by T-Whiz** [comment]
No worries, thanks. 🙂
