### ISSUE TITLE
[Suggestion] Recipes

### ISSUE THREAD

**Issue by Shuggaloaf** [marcstraube/foundryvtt-brodericks-compendium#2]
~~It would be pretty cool to add some "recipes" to craft potions, salves, poultices, etc. from all the plants in the module.~~
Sorry, missed your future plans in the readme. Looking forward to it!! Feel free to close this one out.   

I ran across the "nine herbs charm" on a few items and, since I know my players will immediately ask, I made a recipe for it. Here's one to start you off! (Or for you to ignore for a better one! haha)

<hr/>
<h3>Nine Herbs Charm</h3>

- 2 ounces Psyllium (Plantain Weed)
- 3 tablespoon Mugwort
- 3 tablespoon Watercress
- 1 teaspoon Viper's Bugloss
- 2 teaspoon Thyme
- 4 ounces of Nettle leaves
- 1 teaspoon Fennel seed
- 2 ounces Scented Mayweed flowers
- 4 ounces pulped Crab Apple fruit
- 8 ounces fresh Water
- 6 ounces wood ash
- 1 egg, beaten
- 1 ounce old Soap

1. Using a mortar and pestle, combine: Psyllium, Mugwort, Watercress, Viper's Bugloss, Thyme, Nettle and Mayweed flowers. Crush to a fine power.
2. Mix well with the juice of the Crab Apple and the old Soap until everything is blended.
3. Decant the mixture into a glass jar and seal tightly.
4. Prepare a paste of Water and Ash. Bring to a boil and add Fennel. Boil until cooked down to a paste consistency .
5. Wash the wound with a beaten egg.
6. Pack the wound with the herb mixture.
7. Apply paste over herb mixture and cover with a cloth. 

Every 8 hours the wound should be cleaned and repacked. Rinse the old paste and herb mixture from the skin with clean water. Allow to air for 15 minutes. Re-apply herb mixture and paste as necessary.

**Comment by marcstraube** [comment]
Thanks for your input! This is definitely on my todo list.
