### ISSUE TITLE
V10 Update?

### ISSUE THREAD

**Issue by RinVindor** [marcstraube/foundryvtt-brodericks-compendium#6]
Any chance we can get an update for V10? Thanks for the hard work!

**Comment by marcstraube** [comment]
I'm going to release a new version this weekend. I was just waiting for a stable release and missed it yesterday - thanks for the reminder! ;)

**Comment by RinVindor** [comment]
Just as a heads up, even outside of V10 anytime I try to install the module even manually this error pops up.

![image](https://user-images.githubusercontent.com/12647469/188278420-8ef3c265-3761-46c2-a448-c6b8b3012248.png)
